# Redis Stack modules
loadmodule /opt/redis-stack/lib/redisearch.so
loadmodule /opt/redis-stack/lib/rejson.so
loadmodule /opt/redis-stack/lib/redisbloom.so
loadmodule /opt/redis-stack/lib/redistimeseries.so

# AOF persistence
appendonly yes
appendfilename "appendonly.aof"
appendfsync always

dir /data
# Disable dangerous commands
rename-command FLUSHALL ""
rename-command FLUSHDB ""
# Network & Security
protected-mode no
bind 0.0.0.0
# Memory
maxmemory 0
maxmemory-policy noeviction
