loadmodule /opt/redis-stack/lib/redisearch.so
loadmodule /opt/redis-stack/lib/rejson.so
loadmodule /opt/redis-stack/lib/redisbloom.so
loadmodule /opt/redis-stack/lib/redistimeseries.so

appendonly yes
appendfilename "appendonly.aof"
appendfsync always

# Data directory
# Ensure this matches your EBS mount
dir /data

# Disable dangerous commands
rename-command FLUSHALL ""
rename-command FLUSHDB ""

# Network & security
protected-mode no
bind 0.0.0.0

# Memory eviction policy
maxmemory 0
maxmemory-policy noeviction
